import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sobre nós",
  description: "Conheça a Autodrive Veículos & Tecnologia: compra, venda, financiamento e busca de veículos com atendimento centralizado.",
};
export default function AboutPage() {
  return <><section className="page-hero"><div className="shell"><p className="eyebrow">Autodrive Veículos & Tecnologia</p><h1>Mais opções. Um só atendimento.</h1><p>Conectamos compradores, particulares, lojistas parceiros, financiamento e tecnologia em uma operação automotiva simples de usar.</p></div></section><section className="shell section prose"><h2>Rede de veículos à sua disposição</h2><p>Em vez de depender de um único estoque, reunimos veículos próprios, de lojistas parceiros e de particulares intermediados. Isso amplia as opções de marca, versão, ano e faixa de preço, e aumenta a chance de encontrar exatamente o que você procura.</p><h2>Busca com atendimento centralizado</h2><p>Seu próximo carro pode estar em várias lojas. Você não precisa procurar em todas: conte para a Autodrive o que procura e nossa equipe busca opções dentro da rede de parceiros.</p><h2>Venda assistida para particulares</h2><p>Também intermediamos a compra e a venda entre pessoas, com cuidado na apresentação do veículo, atendimento aos interessados e apoio nos próximos passos da negociação.</p><h2>Parceiros lojistas</h2><p>Os dados comerciais dos parceiros ficam internos. Publicamente, o comprador fala com a Autodrive primeiro, enquanto o painel preserva a origem do veículo, responsável, disponibilidade e demais informações administrativas.</p><h2>Procedência em primeiro lugar</h2><p>Os veículos anunciados têm suas informações apresentadas de forma clara. Consulte a equipe para detalhes de laudo, documentação, garantia, disponibilidade e condições de financiamento.</p></section><section className="shell" style={{ paddingBottom: 48 }}><p className="legal-note">* Somos intermediadores. Garantia, laudo cautelar e procedência são de responsabilidade dos vendedores, conforme cada negociação.</p></section></>;
}
